cleanup chart propnames & rename xCanvas -> xRenderable
bigdatr/pnut pull request #22
Opened 2017-02-09 00:16 UTC by allanhortle

2017-02-09 00:31 UTC, dancoates requested changes
A few super pedantic things

2017-02-09 00:31 UTC, dancoates commented on src/component/Chart.jsx
> + * scales. It checks it's children's props and applies to them these scales configurations it found.
no apostrophe for possessive its.

2017-02-09 00:31 UTC, dancoates commented on src/component/Chart.jsx
> + * scales. It checks it's children's props and applies to them these scales configurations it found.
Also, "to them these scales configurations it found"

2017-02-09 00:31 UTC, dancoates commented on src/component/Chart.jsx
> + * Useage examples might be a correlation graph with independant y axis.
Should probably be "independant y axes"

2017-02-09 00:34 UTC, dxinteractive approved these changes

2017-02-09 00:34 UTC, dxinteractive commented on src/component/Chart.jsx
> + * Useage examples might be a correlation graph with independant y axis.
And "independent" not "independant" haha

2017-02-09 00:35 UTC, dxinteractive commented on src/component/Chart.jsx
> + * Useage examples might be a correlation graph with independant y axis.
And "Usage" not "Useage"

2017-02-14 04:24 UTC, dancoates approved these changes

2017-02-14 04:24 UTC, merged