Feature/histogram
bigdatr/pnut pull request #46
Opened 2017-03-06 02:52 UTC by dancoates

- Adds ChartData.bin method to bin data
- Adds some other ChartData aggregation methods from d3-array that will be handy for box & whisker and bell curve charts.
- Updates Chart.jsx to allow specifying multiple columns for a dimension on a single chart.
- Adds histogram components

Make sure you expand the diff on CharData.js

One potentially controversial update is separating the memoization of getting column values from `ChartData._allValuesForColumns` and the memoization of aggregate functions. This should in theory speed up things like `extent` which make sequential calls to min and max with and previously would generate the same list of values twice. It also allows for partial memoization of new aggregation methods like `quantile` which can't be fully memoized as it accepts a second parameter which is a float. This update will have a memory cost but I think the trade of is probably worth it... I'm not 100% on that so feel free to convince me otherwise if you disagree.

2017-03-06 03:00 UTC, allanhortle approved these changes

2017-03-06 03:00 UTC, allanhortle commented on src/component/Chart.jsx
> +                        const newDimensions = columns.reduce((
Can you put some comments here documenting the intent of this part? Trying to keep the business logic in Chart rememberable.

2017-03-06 03:38 UTC, dancoates commented on src/component/Chart.jsx
> +                        const newDimensions = columns.reduce((
Good point, I've updated with some comments.

2017-03-08 02:44 UTC, dxinteractive requested changes

2017-03-08 02:44 UTC, dxinteractive commented on src/chartdata/__test__/ChartData-aggregations-test.js
> +test('ChartData.summary should return map with nulls when provided a column that doesnt exist', tt => {
Is this meant to return a map with nulls or just null? Test and descriptions don't match here

2017-03-08 03:22 UTC, dxinteractive approved these changes

2017-03-08 03:37 UTC, merged